repos:
-   repo: https://github.com/python/black
    rev: stable
    hooks:
    -   id: black
-   repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
default_language_version:
    python: python3.8
