language: python
python:
    - "3.6"

install:
  - pip3 install pipenv
  - pipenv install -d --system --three


script:
  - nosetests

notifications:
  email:
    recipients:
      - asoli@fb.com
    on_failure: change # default: always
